name: 'The Action Name'
description: 'The action description'
inputs:
  token:
    description: Token to use for Github API
    required: true
    default: ${{ github.token }}
  repoInfo:
    description: Owner and name of current repository
    required: true
    default: ${{ GITHUB_REPOSITORY }}

outputs:
  output:
    description: Not yet
  
runs:
  using: 'node12'
  main: 'release/index.js'